### ISSUE TITLE
add status of development to readme

### ISSUE THREAD

**Issue by clayly** [rsocket/rsocket-py#13]
It's not clear what status of development is.

## Documentation Issue

There is no status of development in readme.
## Improvement Suggestion

Add status of development to readme.
## Additional context

There is opened issue https://github.com/rsocket/rsocket-py/issues/6. There is a link to potential explanation of development status https://community.netifi.com/t/future-direction-of-python-implementation-of-rsocket/158. But linked resource is not available anymore. Anyway it's more appropriate to add this kind of information to readme.

**Comment by gabis-precog** [comment]
Done. please open issue about specific missing items.
