### ISSUE TITLE
Release new official package (v0.3)

### ISSUE THREAD

**Issue by wtj0906** [rsocket/rsocket-py#37]
When will you upload the program as a module to PyPi? The version on PyPi is quite old. I'm writing a rsocket client connecting to a java rsocket server. It would be much easier to use if I could introduce rsocket-py as a module.

**Comment by gabis-precog** [comment]
@wtj0906 currently attempting to get the pypi credentials as the maintainer of the official package cannot be contacted.
A ticket was opened with pypi. It may take time.

**Comment by gabis-precog** [comment]
https://pypi.org/project/rsocket/0.3.dev1/ available for testing
