### ISSUE TITLE
How to set the number of reconnections on connection lost?

### ISSUE THREAD

**Issue by wtj0906** [rsocket/rsocket-py#48]
How to set the number of reconnections on connection lost? Currently it seems that the client will keep reconnecting...

**Comment by gabis-precog** [comment]
@wtj0906 
can you please attach some code and expected behavior ?

**Comment by gabis-precog** [comment]
@wtj0906 check out [reconnect_flow_fix_and_example](https://github.com/rsocket/rsocket-py/tree/reconnect_flow_fix_and_example) branch. added an example for reconnection in the examples folder, and fixed the reconnect flow a bit.

**Comment by gabis-precog** [comment]
merged fixes to master. @wtj0906 please reopen if still not clear.
