### ISSUE TITLE
Runtime error in the example code for the client

### ISSUE THREAD

**Issue by runflowcode** [rsocket/rsocket-py#5]
I am getting a runtime error on the client code provided in your example.

`RR: <payload: 'The quick brown fox jumps over the lazy dog.', 'Escher are an artist.'>
RuntimeError(bytearray(b'Not implemented'))
RS: error: bytearray(b'Not implemented')`

**Comment by runflowcode** [comment]
Is there anyone managing the repo ?

**Comment by robertroeser** [comment]
FYI-
https://community.netifi.com/t/future-direction-of-python-implementation-of-rsocket/158

**Comment by tstordyallison** [comment]
The link above seems to be dead...

anyone got a tldr? 

(For context, I’m trying to implement a client for ‘Flipper’, the Facebook devtool. I think what’s here in this repo so far might actually be enough).
