### ISSUE TITLE
RSocketClient generating "Not implemented" for request_response

### ISSUE THREAD

**Issue by agapebondservant** [rsocket/rsocket-py#82]
Hello team, I'm reaching out because I'm encountering an issue as I attempt to perform a _request_response_ with the RSocketClient. I used the examples provided [here](https://github.com/rsocket/rsocket-py/blob/master/examples/client.py) and [here](https://github.com/rsocket/rsocket-py/blob/master/examples/shared_tests.py).

## Expected Behavior

Should not return any errors.

## Actual Behavior

Generating the default BaseRequestHandler's response - unsure of how to ensure that it's using the ClientHandler implementation instead.

Stacktrace:
Error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mlmetrics/exporter.py", line 82, in run_request_response
    result = await client.request_response(payload)
RuntimeError: Request-Response not implemented.

## Steps to Reproduce

Here's my RequestHandler impl (originally tried using BaseRequestHandler - basically mostly copy-pasted to help with troubleshooting):
```
class ClientHandler(RequestHandler):

        async def on_setup(self, data_encoding: bytes, metadata_encoding: bytes, payload: Payload):
            """Nothing to do on setup by default"""

        async def request_response(self, payload: Payload):
            logger.info("In request_response method...")
            return create_future(Payload(b'' + payload.data + b'',
                                         b'' + payload.metadata + b''))

        async def request_channel(self, payload: Payload):
            raise RuntimeError('Not implemented')

        async def request_fire_and_forget(self, payload: Payload):
            """The requester isn't listening for errors.  Nothing to do."""

        async def on_metadata_push(self, payload: Payload):
            """Nothing by default"""

        async def request_stream(self, payload: Payload):
            raise RuntimeError('Not implemented')

        async def on_error(self, error_code, payload: Payload):
            logger.error('Error handler: %s, %s', error_code.name, payload)

        async def on_connection_error(self, rsocket, exception):
            pass

        async def on_close(self, rsocket, exception=None):
            pass

        async def on_keepalive_timeout(self, time_since_last_keepalive, rsocket):
            pass
```

Relevant Client code snippet:

```
async with RSocketClient(single_transport_provider(TransportTCP(*connection)), handler_factory=ClientHandler) as client:

        async def run_request_response():

            try:
                while True:
                    sent = '{"my":"jsondata"}'
                    payload = Payload(sent)
                    result = await client.request_response(payload)
                    received = result.data
            except Exception as e:
                logger.error('Error occurred: ', exc_info=True)
                pass
        
         await run_request_response()

```

## Your Environment

* RSocket version(s) used: 0.4.4
* Other relevant libraries versions (eg. `netty`, ...): 
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)): 
* OS and version (eg `uname -a`): Mac

**Comment by jell-o-fishi** [comment]
what server are you trying to connect to ?

**Comment by agapebondservant** [comment]
I see. The server is a third party service that supports RSocket connections from clients, so I only have control over the client side. Does it mean that I actually don't have to implement any handler on the client side?

**Comment by agapebondservant** [comment]
(I'm a newbie to the RSocket protocol in general)

**Comment by jell-o-fishi** [comment]
Unless the server will issue requests back to the client, then no, the client doesn't need a handler.
The requests to the server need to follow the api available from it. from the response I see that a simple request_response is not implemented.

Check the server's api, and probably the example which involves routing (server_with_routing.py / client_with_routing.py)

**Comment by agapebondservant** [comment]
Thanks!
